INSERT INTO pruebagood.news_post (name) VALUES 
('Home Slider')
,('Inscripción a nuestros cursos, semilleros y seleccionados')
,('Nuevo edificio de residencias universitarias en Unicauca')
,('Agenda Semana Santa 2019')
,('Conmemoración 8 de Marzo')
,('Pre registro para Jóvenes en Acción Universidad del Cauca.')
,('¡Ya puedes acercarte a reclamar tu souvenir!')
,('Taller de Juegos tradicionales y autóctonos “Namui – Namui”')
,('Feria EmprendeSer')
,('Feria EmprendeSer')
;
INSERT INTO pruebagood.news_post (name) VALUES 
('¡Ven y rueda con nosotros! III Rodada Universitaria')
,('Primer Conversatorio de Diálogos Interculturales Popayán 2019')
,('Segundo Conversatorio Diálogos Interculturales 2019 La Sierra(C)')
,('Avance Ruta de Atención Para Casos de Violencia de Género')
,('II Juegos Intra-Facultades')
,('Iniciamos  “Unicauca Activa de Corazón”')
,('Divulgación de Participantes Feria EmprendeSer')
,('Categorías Educación y Cultura')
,('Diálogos Interculturales')
,('Torneo Interfacultades para Docentes y Administrativos')
;
INSERT INTO pruebagood.news_post (name) VALUES 
('Continuamos con la Feria EmprendeSer')
,('¡Llego la hora de ejercitarnos y saber sobre nuestra salud!')
,('ACTUALIZACIÓN Y RENOVACIÓN DE CRÉDITOS ICETEX 2019/1')
,('Programa de Jóvenes en Acción')
,('II Encuentro Internacional de Guitarra Clásica')
,('SER ESTUDIOSO CUENTA')
,('Resolución VRA 265 de 2019 (Se otorga permiso académico)')
,('¡Todos al CDU!')
,('Unicauca se Activa de Corazón')
,('Torneo Interfacultades Mixto Baloncesto - Docentes y Admin')
;
INSERT INTO pruebagood.news_post (name) VALUES 
('Se acerca noche de museos')
,('Red de Padres Unicauca')
,('Hacia una Política Institucional de Inclusión')
,('5 Conv. Estímulos Proyectos de Cultura y Bienestar 2019')
,('Sexto Premio Regional de Arte Universitario 2019')
,('Ser Estudioso Cuenta')
,('Taller de Participantes Jóvenes en Acción')
,('Diálogos Interculturales en Santander de Quilichao')
,('Diálogos Interculturales en Santander de Quilichao')
,('Día del Estudiante en Sede Santander de Quilichao')
;
INSERT INTO pruebagood.news_post (name) VALUES 
('Salud en Movimiento')
,('La actitud, clave para cumplir metas')
,('Avanza política educación inclusiva en nuestra Alma Mater')
,('Convocatoria para formar parte Colectivo Musical VCB')
,('Unicauca Activa de Corazón, Sede Norte Santander de Quilichao')
,('Cierre de ciclo de Conferencias')
,('El Cuerpo en las Artes')
,('Inscripciones para el Voluntariado SSU 2019-II')
,('Temporada Música Instrumental')
,('Cuentos para salvar el semestre')
;
INSERT INTO pruebagood.news_post (name) VALUES 
('Unicauca Activa de Corazón: FIET en movimiento')
,('Posesión Rep. Estudiantes ante Consejo Cultura y Bienestar')
,('¡Unicauca está sonando!')
,('Temporada Musical 2019 Presenta: Ciprés Trío')
,('Adenda Nº1 Convocatoria 2019 de Cultura y Bienestar')
,('Adenda Nº 1 Convocatoria 2019 de Cultura y Bienestar')
,('Bienvenidos a tu Universidad')
,('Bienvenidos Unicaucanos')
,('¿Qué es Generación E?')
,('Inscripciones a Cursos Recreativos')
;
INSERT INTO pruebagood.news_post (name) VALUES 
('Adenda Nº 1 Convocatoria de Cultura y Bienestar')
,('Muestra de Emprendimientos Culturales y Creativos')
,('Unicaucanos rumbo a los nacionales')
,('Reflexión Universitaria ')
,('Jóvenes en acción')
,('Ser Estudioso Cuenta')
,('Inscripciones Talleres Formación Artística')
,('Dialogos Interculturales')
,('Enculturate Facultad de Ciencias de la Salud')
,('Comunicado de la Vicerrectoría de Cultura y Bienestar')
;
INSERT INTO pruebagood.news_post (name) VALUES 
('Taller informativo y Pre registro para Jóvenes en Acción')
,('Jornada de Salud Oral en tu Facultad')
,('I Encuentro de Género y etnicidad')
,('Jornada de Salud Oral')
,('Ser Estudioso Cuenta - Apoyo formulación de perfiles')
,('Jornada de Salud Oral - Facultad de Artes')
,('¡Esta semana la cita es con el teatro!')
,('Jornada de Salud Oral - Facultad de Ciencias Humanas')
,('¡Unicauca está sonando!')
,('EFEMÉRIDES UNIVERSIDAD DEL CAUCA')
;
INSERT INTO pruebagood.news_post (name) VALUES 
('¡Popayán Ciudad Libro 2019 ya está aquí!')
,('Encuesta Da Satisfacción Del Servicio De Cafeterías')
,('Semana de la Cultura y Bienestar Universitario')
,('IV Rodada Universitaria Bike Unicauca')
;
